README.md, go/cmd/f/main.go, go/go.mod, go/http/instance.go, go/http/service.go, go/http/service_test.go
Creates the basic structure for Go func runtime
=> Initial commit

go/http/instance.go
Sets up single-method interfaces for event handlers such as 'Stopper', 'Starter', 'ReadinessReporter' etc.
=> Update to separate single-method interfaces

go/http/service.go
Implements default readiness and liveness probes, allowing function instances to override with their own implementation.
=> feat: readiness and liveness probes

go/http/service_test.go
=> feat: test stubs

go/http/instance.go, go/http/service.go
Sets up readiness and liveness typseafe with context.
=> readiness and liveness language typesafe with context

go/cloudevents/instance.go, go/cloudevents/service.go, go/cloudevents/service_test.go, go/cmd/fce-send/main.go, go/cmd/fce/main.go, go/cmd/fhttp/main.go, go/go.mod
Enable (initial) CloudEvents support.
This is not complete.
=> feat: initial cloudevents support

go/http/service.go
:broom: remove debug statments
/kind cleanup
=> src: remove debugging statements

go/http/instance.go, go/http/mock/function.go, go/http/service.go, go/http/service_test.go
:gift: onstart handler nonblocking
=> feat: nonblocking onstart handler

go/http/service.go
:gift: Print effective runtime version on load.
/kind enhancement
=> feat: version echo on load

go/http/service.go
:gift: Extended debug logging
/kind enhancement
=> feat: extended debug

http/instance.go, http/mock/function.go, http/service.go, http/service_test.go
:gift: graceful startup and shutdowns
/kind enhancement
=> feat: graceful startup and shutdown

cmd/fce/main.go, cmd/fhttp/main.go
:broom: update test command imports
/kind cleanup
=> src: update test cmd imports

cmd/fce/main.go, cmd/fhttp/main.go, go.mod
:broom: update package name
/kind cleanup
=> src: update module and cmd imports

http/service.go
:broom: improved health endpoint logging
/kind cleanup
=> src: improved ready and liveness logging

http/service.go
:gift: listen address env var
/kind enhancement
=> feat: listen address

http/service.go
:broom: simplified logging/reporting
/kind cleanup
=> src: simplified listen address reporting and logging

cloudevents/service.go, http/service.go
:broom: filter SIGURG
/kind cleanup
=> src: filter SIGURG

cloudevents/service.go, http/service.go
=> fix: ignore signal 23 in linux

http/service.go, http/service_test.go
=> feat: static config

http/mock/function.go, http/service.go, http/service_test.go
:gift: support LISTEN_ADDRESS
:gift: print implemented interfaces on instantiation
:gift: more tests
:gift: better logging
=> feat: support LISTEN_ADDRESS 

cloudevents/instance.go, http/service_test.go
- trivial change: fixing typos on comments
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> chore: fixing simple typo

cloudevents/service.go
- as per title (makes porting other code easier, hence doing before)
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Align param names to their peer in http service

cloudevents/logs.go, cloudevents/service.go
- :gift: New strucuted logging for CloudEvents
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Cloudevent logging

cmd/fce/main.go
- :broom: Updating sample as per title, and aligning with HTTP, which also has more meaningful handler
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Adding more meaningful example CE handler, aligning with the func/templates

cloudevents/mock/function.go
- :broom: Following up on #40, providing a mock for further testing that is using same signature for the handler
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Adding a simple mock for a common CE function

cloudevents/service_test.go
- :broom: Enabling simple start tests
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Adding simple CE start test

cloudevents/service.go
- inline request handling (like http)
- introduce startInstance
- change env var handling
- remove MyFunc/debugger (was not needed)
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Refactoring more of CE to be more aligned with http module

cloudevents/service.go, cloudevents/service_test.go
- service listenr and improvements
- f any handler
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Use service listener and do f any handler

cloudevents/service_test.go
- :broom: Add CE handler test
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Add test for CE handler

http/service_test.go
- :broom: Adding test for alive/ready default handlers
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> HTTP: Adding test for alive/ready default handlers

cloudevents/service.go, cloudevents/service_test.go
- :broom: Fully leverage the `listener` on the server, was oversight and broken before
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Fix problem with binding and test for real port

cloudevents/service_test.go, http/service_test.go
- :broom: Add tests
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Adding tests for READY and ALIVE

cloudevents/service_test.go, http/service_test.go
- As per title
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Adding timeout channel

OWNERS
- as per title
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Adding matzew as approver

cloudevents/service.go
- :broom: removing since it was forgotten when finishing refactorings
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Remove service port constant

cloudevents/service_test.go, http/service_test.go
- improving tests
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Adding timeout channel to the rest of the test suite

cloudevents/service_test.go, http/service_test.go
- :broom: Update tests so they have similar structure / shape
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Adjusting tests, so they are more similar

go.mod, go.sum, hack/tools.go, hack/update-codegen.sh, hack/update-deps.sh, hack/verify-codegen.sh, third_party/VENDOR-LICENSE/github.com/cloudevents/sdk-go/v2/LICENSE, third_party/VENDOR-LICENSE/github.com/google/uuid/LICENSE, third_party/VENDOR-LICENSE/github.com/json-iterator/go/LICENSE, third_party/VENDOR-LICENSE/github.com/mattn/go-colorable/LICENSE, third_party/VENDOR-LICENSE/github.com/mattn/go-isatty/LICENSE, third_party/VENDOR-LICENSE/github.com/modern-go/concurrent/LICENSE, third_party/VENDOR-LICENSE/github.com/modern-go/reflect2/LICENSE, third_party/VENDOR-LICENSE/github.com/rs/zerolog/LICENSE, third_party/VENDOR-LICENSE/go.uber.org/multierr/LICENSE.txt, third_party/VENDOR-LICENSE/go.uber.org/zap/LICENSE, third_party/VENDOR-LICENSE/golang.org/x/sys/unix/LICENSE, third_party/VENDOR-LICENSE/knative.dev/func-go/LICENSE
Adds the various knative maintenance tools in the `./hack` directory, and commits the results of running update-deps.sh
/kind chore
=> chore: install maintenance scripts

cloudevents/service.go
- as per title
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> CE service impl. using Fprint with writer, instead of direct writer call

cloudevents/service.go, http/service.go
- :broom: Update to use well established constants
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> chore: Using constants instead of hard-coded vals
